name: Update Weekly Content Page

on:
  # Scheduled weekly update every Thursday at 6 AM ET (10 AM UTC)
  schedule:
    - cron: '0 10 * * 4'

  # Allows manual triggering of the action for testing
  workflow_dispatch:

jobs:
  update-weekly-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure we get the full history for pushes

      # Process "lastweekstrivia" page
      - name: Find the Existing "lastweekstrivia" Page
        id: find_existing_trivia
        run: |
          # Find the existing lastweekstrivia*.html file
          EXISTING_PAGE=$(ls lastweekstrivia*.html | head -n 1 || echo "")
          echo "Found existing trivia page: $EXISTING_PAGE"
          echo "::set-output name=existing_page::$EXISTING_PAGE"

      - name: Copy Content from Existing "lastweekstrivia" Page (if it exists)
        if: ${{ steps.find_existing_trivia.outputs.existing_page != '' }}
        id: copy_content_trivia
        run: |
          # Read content from the existing page
          EXISTING_PAGE="${{ steps.find_existing_trivia.outputs.existing_page }}"
          PAGE_CONTENT=$(cat "$EXISTING_PAGE")
          
          # Generate a random 8-character string for the new page URL
          RANDOM_SUFFIX=$(openssl rand -hex 4)
          NEW_PAGE_NAME="lastweekstrivia${RANDOM_SUFFIX}.html"
          
          # Write the content to the new page
          echo "$PAGE_CONTENT" > "$NEW_PAGE_NAME"
          
          echo "New trivia page created: $NEW_PAGE_NAME with copied content"
          echo "::set-output name=new_page_name::$NEW_PAGE_NAME"

      - name: Delete old "lastweekstrivia" page
        if: ${{ steps.find_existing_trivia.outputs.existing_page != '' }}
        run: |
          # Remove the old lastweekstrivia page
          rm -f "${{ steps.find_existing_trivia.outputs.existing_page }}"
          echo "Deleted old lastweekstrivia page."

      # Process "lastweeksanswers" page
      - name: Find the Existing "lastweeksanswers" Page
        id: find_existing_answers
        run: |
          # Find the existing lastweeksanswers*.html file
          EXISTING_PAGE=$(ls lastweeksanswers*.html | head -n 1 || echo "")
          echo "Found existing answers page: $EXISTING_PAGE"
          echo "::set-output name=existing_page::$EXISTING_PAGE"

      - name: Copy Content from Existing "lastweeksanswers" Page (if it exists)
        if: ${{ steps.find_existing_answers.outputs.existing_page != '' }}
        id: copy_content_answers
        run: |
          # Read content from the existing page
          EXISTING_PAGE="${{ steps.find_existing_answers.outputs.existing_page }}"
          PAGE_CONTENT=$(cat "$EXISTING_PAGE")
          
          # Generate a random 8-character string for the new page URL
          RANDOM_SUFFIX=$(openssl rand -hex 4)
          NEW_PAGE_NAME="lastweeksanswers${RANDOM_SUFFIX}.html"
          
          # Write the content to the new page
          echo "$PAGE_CONTENT" > "$NEW_PAGE_NAME"
          
          echo "New answers page created: $NEW_PAGE_NAME with copied content"
          echo "::set-output name=new_page_name_answers::$NEW_PAGE_NAME"

      - name: Delete old "lastweeksanswers" page
        if: ${{ steps.find_existing_answers.outputs.existing_page != '' }}
        run: |
          # Remove the old lastweeksanswers page
          rm -f "${{ steps.find_existing_answers.outputs.existing_page }}"
          echo "Deleted old lastweeksanswers page."

      - name: List Files in Repository
        run: |
          echo "Listing files in the repository after creating the new pages and deleting the old ones:"
          ls -l

      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Add the new pages and remove the deleted file(s) from Git
          git add -A
          
          # Check Git status to see if the files were staged correctly
          git status
          
          git commit -m "Add weekly content pages ${{ steps.copy_content_trivia.outputs.new_page_name }} and ${{ steps.copy_content_answers.outputs.new_page_name_answers }}" || echo "No changes to commit"
          git push origin HEAD || echo "No changes to push"

      - name: Display new page URLs
        run: |
          echo "New trivia page URL: https://eviltrivia.com/${{ steps.copy_content_trivia.outputs.new_page_name }}"
          echo "New answers page URL: https://eviltrivia.com/${{ steps.copy_content_answers.outputs.new_page_name_answers }}"

      - name: Summarize the New URLs
        if: always()
        run: |
          echo "Weekly Trivia page is now live at: https://eviltrivia.com/${{ steps.copy_content_trivia.outputs.new_page_name }}"
          echo "Weekly Answers page is now live at: https://eviltrivia.com/${{ steps.copy_content_answers.outputs.new_page_name_answers }}"
