name: Update Weekly Content Page

on:
  # Scheduled weekly update every Thursday at 6 AM ET (10 AM UTC)
  schedule:
    - cron: '0 10 * * 4'

  # Allows manual triggering of the action for testing
  workflow_dispatch:

jobs:
  update-weekly-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure we get the full history for pushes

      - name: Delete old "lastweekstrivia" page
        run: |
          # Remove any existing file that starts with "lastweekstrivia"
          rm -f lastweekstrivia*.html
          echo "Deleted old lastweekstrivia pages if any existed."

      - name: Generate new page with randomized URL
        id: generate_page
        run: |
          # Generate a random 8-character string for the URL suffix
          RANDOM_SUFFIX=$(openssl rand -hex 4)
          PAGE_NAME="lastweekstrivia${RANDOM_SUFFIX}.html"
          
          # Base64 encode the Google Sheets URL
          SHEET_URL="https://docs.google.com/spreadsheets/d/e/2PACX-1vQrinTI3oQF6YzefZ48deronxXq5WScORt5Vl-W73GODSvKa7JJAF94BmVsg0AwqjhpVfZy4QfJHxug/pubhtml?gid=672502672&single=true"
          ENCODED_URL=$(echo -n "$SHEET_URL" | base64)
          
          # Create the HTML content with JavaScript to decode and load the URL
          echo "<!DOCTYPE html>
          <html>
          <head>
            <title>Weekly Trivia</title>
            <script type='text/javascript'>
              console.log('Script loaded');
              document.addEventListener('DOMContentLoaded', function() {
                console.log('DOMContentLoaded event fired');
                var encodedUrl = '$ENCODED_URL';
                try {
                  var decodedUrl = atob(encodedUrl);
                  console.log('Decoded URL:', decodedUrl);
                  var iframe = document.createElement('iframe');
                  iframe.src = decodedUrl;
                  iframe.width = '100%';
                  iframe.height = '2400';
                  iframe.style.border = 'none';
                  document.body.appendChild(iframe);
                } catch (error) {
                  console.error('Error decoding URL:', error);
                }
              });
            </script>
          </head>
          <body>
            <noscript>
              You need to enable JavaScript to view this content.
            </noscript>
          </body>
          </html>" > "$PAGE_NAME"
      
          echo "New page generated: $PAGE_NAME"
          echo "::set-output name=page_url::https://eviltrivia.com/$PAGE_NAME"
          echo "::set-output name=page_name::$PAGE_NAME"

      - name: List Files in Repository
        run: |
          echo "Listing files in the repository after generating the new page:"
          ls -l

      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Add the new page and remove the deleted file(s) from Git
          git add -A
          
          # Check Git status to see if the files were staged correctly
          git status
          
          git commit -m "Add weekly content page ${{ steps.generate_page.outputs.page_name }}" || echo "No changes to commit"
          git push origin HEAD || echo "No changes to push"

      - name: Display new page URL
        run: |
          echo "New page URL: ${{ steps.generate_page.outputs.page_url }}"

      - name: Summarize the New URL
        if: always()
        run: |
          echo "Weekly Trivia page is now live at: ${{ steps.generate_page.outputs.page_url }}"
