name: Update Weekly Content Page

on:
  # Scheduled weekly update every Sunday at midnight UTC
  schedule:
    - cron: '0 0 * * 0'

  # Allows manual triggering of the action for testing
  workflow_dispatch:

jobs:
  update-weekly-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure we get the full history for pushes

      - name: Generate new page with randomized URL
        id: generate_page
        run: |
          # Generate a random 8-character string for the URL suffix
          RANDOM_SUFFIX=$(openssl rand -hex 4)
          PAGE_NAME="lastweekstrivia${RANDOM_SUFFIX}.html"
          
          # Create the HTML content with the consistent Google Sheet link
          echo "<!DOCTYPE html><html><head><title>Weekly Trivia</title></head><body><iframe src='https://docs.google.com/spreadsheets/d/e/2PACX-1vQrinTI3oQF6YzefZ48deronxXq5WScORt5Vl-W73GODSvKa7JJAF94BmVsg0AwqjhpVfZy4QfJHxug/pubhtml?gid=672502672&single=true' width='100%' height='600'></iframe></body></html>" > "$PAGE_NAME"

          echo "New page generated: $PAGE_NAME"
          echo "::set-output name=page_url::https://eviltrivia.com/$PAGE_NAME"
          echo "::set-output name=page_name::$PAGE_NAME"

      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add "${{ steps.generate_page.outputs.page_name }}"
          git commit -m "Add weekly content page ${{ steps.generate_page.outputs.page_name }}" || echo "No changes to commit"
          git push origin HEAD || echo "No changes to push"

      - name: Display new page URL
        run: |
          echo "New page URL: ${{ steps.generate_page.outputs.page_url }}"
