name: Update Weekly Content Page

on:
  # Scheduled weekly update every Thursday at 6 AM ET (10 AM UTC)
  schedule:
    - cron: '0 10 * * 4'

  # Allows manual triggering of the action for testing
  workflow_dispatch:

jobs:
  update-weekly-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure we get the full history for pushes

      # Step 1: Find and Delete Existing Pages
      - name: Find and delete old "lastweekstrivia" and "lastweeksanswers" pages
        run: |
          # Remove any existing file that starts with "lastweekstrivia" or "lastweeksanswers"
          rm -f lastweekstrivia*.html lastweeksanswers*.html
          echo "Deleted old lastweekstrivia and lastweeksanswers pages if any existed."

      # Step 2: Create New "lastweekstrivia" Page
      - name: Copy Content from Existing "lastweekstrivia" Page (if it exists)
        id: create_trivia_page
        run: |
          # Generate a random suffix for the new page
          RANDOM_SUFFIX=$(openssl rand -hex 4)
          NEW_TRIVIA_PAGE="lastweekstrivia${RANDOM_SUFFIX}.html"

          # Create new trivia page content
          echo "<!DOCTYPE html>
          <html lang='en'>
          <head>
            <meta charset='UTF-8'>
            <title>Last Week's Trivia</title>
          </head>
          <body>
            <p>This is the latest trivia page.</p>
          </body>
          </html>" > "$NEW_TRIVIA_PAGE"

          echo "New trivia page created: $NEW_TRIVIA_PAGE"
          echo "::set-output name=trivia_page_name::$NEW_TRIVIA_PAGE"

      # Step 3: Create New "lastweeksanswers" Page
      - name: Copy Content from Existing "lastweeksanswers" Page (if it exists)
        id: create_answers_page
        run: |
          # Generate a random suffix for the new page
          RANDOM_SUFFIX=$(openssl rand -hex 4)
          NEW_ANSWERS_PAGE="lastweeksanswers${RANDOM_SUFFIX}.html"

          # Create new answers page content
          echo "<!DOCTYPE html>
          <html lang='en'>
          <head>
            <meta charset='UTF-8'>
            <title>Last Week's Answers</title>
          </head>
          <body>
            <p>This is the latest answers page.</p>
          </body>
          </html>" > "$NEW_ANSWERS_PAGE"

          echo "New answers page created: $NEW_ANSWERS_PAGE"
          echo "::set-output name=answers_page_name::$NEW_ANSWERS_PAGE"

      # Step 4: Update latest_pages.json with the new URLs
      - name: Update latest_pages.json
        run: |
          echo '{
            "lastweekstrivia": "https://eviltrivia.com/${{ steps.create_trivia_page.outputs.trivia_page_name }}",
            "lastweeksanswers": "https://eviltrivia.com/${{ steps.create_answers_page.outputs.answers_page_name }}"
          }' > latest_pages.json
          git add latest_pages.json
          echo "Staged latest_pages.json for commit."
          git status
          git diff --staged

      # Step 5: Commit and push the changes
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Commit only if there are changes
          git commit -m "Update latest trivia and answers pages" || echo "No changes to commit"
          git push origin HEAD || echo "No changes to push"

      - name: List Files in Repository for Verification
        run: ls -l
