name: Update Weekly Content Page

on:
  # Scheduled weekly update every Thursday at 6 AM ET (10 AM UTC)
  schedule:
    - cron: '0 10 * * 4'

  # Allows manual triggering of the action for testing
  workflow_dispatch:

jobs:
  update-weekly-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure we get the full history for pushes

      - name: Delete old "lastweekstrivia" page
        run: |
          # Remove any existing file that starts with "lastweekstrivia"
          rm -f lastweekstrivia*.html
          echo "Deleted old lastweekstrivia pages if any existed."

      - name: Create HTML Page with Obfuscated URL
        id: create_html
        run: |
          # Generate a random 8-character string for the URL suffix
          RANDOM_SUFFIX=$(openssl rand -hex 4)
          PAGE_NAME="lastweekstrivia${RANDOM_SUFFIX}.html"
          
          # Define the Google Sheets URL as an array of characters
          SHEET_URL_ARRAY="['h','t','t','p','s',':','/','/','d','o','c','s','.','g','o','o','g','l','e','.','c','o','m','/','s','p','r','e','a','d','s','h','e','e','t','s','/','d','/','e','/','2','P','A','C','X','-','1','v','Q','r','i','n','T','I','3','o','Q','F','6','Y','z','e','f','Z','4','8','d','e','r','o','n','x','X','q','5','W','S','c','O','R','t','5','V','l','-','W','7','3','G','O','D','S','v','K','a','7','J','J','A','F','9','4','B','m','V','s','g','0','A','w','q','j','h','p','V','f','Z','y','4','Q','f','J','H','x','u','g','/','p','u','b','h','t','m','l','?','g','i','d','=','6','7','2','5','0','2','6','7','2','&','s','i','n','g','l','e','=','t','r','u','e']"

          # Create the HTML content with JavaScript to reconstruct the URL
          echo "<!DOCTYPE html>
          <html>
          <head>
            <title>Weekly Trivia</title>
            <script type='text/javascript'>
              document.addEventListener('DOMContentLoaded', function() {
                var sheetUrlArray = $SHEET_URL_ARRAY;
                var decodedUrl = sheetUrlArray.join('');
                console.log('Decoded URL:', decodedUrl);  // Log to confirm correct URL
                var iframe = document.createElement('iframe');
                iframe.src = decodedUrl;
                iframe.width = '100%';
                iframe.height = '2400';
                iframe.style.border = 'none';
                document.body.appendChild(iframe);
              });
            </script>
          </head>
          <body>
            <noscript>
              You need to enable JavaScript to view this content.
            </noscript>
          </body>
          </html>" > "$PAGE_NAME"
      
          echo "New page generated: $PAGE_NAME"
          echo "::set-output name=page_url::https://eviltrivia.com/$PAGE_NAME"
          echo "::set-output name=page_name::$PAGE_NAME"

      - name: List Files in Repository
        run: |
          echo "Listing files in the repository after generating the new page:"
          ls -l

      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Add the new page and remove the deleted file(s) from Git
          git add -A
          
          # Check Git status to see if the files were staged correctly
          git status
          
          git commit -m "Add weekly content page ${{ steps.create_html.outputs.page_name }}" || echo "No changes to commit"
          git push origin HEAD || echo "No changes to push"

      - name: Display new page URL
        run: |
          echo "New page URL: ${{ steps.create_html.outputs.page_url }}"

      - name: Summarize the New URL
        if: always()
        run: |
          echo "Weekly Trivia page is now live at: ${{ steps.create_html.outputs.page_url }}"
